version: '3.8'

services:

  led-controller:
    image: canadrian72/iot-control-center:led-controller
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

