version: '3.7'

services:

  led-controller:
    image: canadrian72/iot-control-center:led-controller
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5683:5683/udp"

