version: '3.7'

services:

  led-controller:
    image: canadrian72/iot-control-center:led-controller
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1883
    environment:
      - BROKER_IP=10.0.0.35

