version: '3.8'

services:

  api:
    image: canadrian72/iot-control-center:lighting-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "8000:8000"
