version: '3.8'

services:
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - ~/iot-control-center/DeviceDatabase/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iot_admin
      - MONGO_INITDB_ROOT_PASSWORD=iot_password

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=iot_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=iot_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb:mongodb

