apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: iot-control-center
      svc: api
  replicas: 3
  template:
    metadata:
      labels:
        app: iot-control-center
        svc: api
    spec:
      containers:
        - name: api-container
          image: canadrian72/iot-control-center:api
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8000
