apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulb-2-controller
spec:
  selector:
    matchLabels:
      app: iot-control-center
  replicas: 2
  template:
    metadata:
      labels:
        app: iot-control-center
    spec:
      containers:
        - name: bulb-2-controller-container
          image: canadrian72/iot-control-center:bulb-2-controller
          imagePullPolicy: Always
          ports:
            - containerPort: 1883
            - containerPort: 9999
