apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-database
spec:
  selector:
    matchLabels:
      svc: device-database
  replicas: 1
  template:
    metadata:
      labels:
        svc: device-database
    spec:
      containers:
        - name: device-database-container
          image: canadrian72/iot-control-center:device-database
          imagePullPolicy: Always
