apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighting-api
spec:
  selector:
    matchLabels:
      app: iot-control-center
      svc: lighting-api
  replicas: 2
  template:
    metadata:
      labels:
        app: iot-control-center
        svc: lighting-api
    spec:
      containers:
        - name: lighting-api-container
          image: canadrian72/iot-control-center:lighting-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
