apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighting-api
spec:
  selector:
    matchLabels:
      svc: lighting-api
  replicas: 2
  template:
    metadata:
      labels:
        svc: lighting-api
    spec:
      containers:
        - name: lighting-api-container
          image: canadrian72/iot-control-center:lighting-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_DB_USERNAME
              value: ${MONGO_DB_USERNAME}
            - name: MONGO_DB_PASSWORD
              value: ${MONGO_DB_PASSWORD}
