version: '3.7'

services:

  api:
    image: canadrian72/iot-control-center:api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - BROKER_IP=10.0.0.34
